
package com.fincore.cbpcarrierwebservice.exemplar;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.fincore.cbpcarrierwebservice.CarrierService;
import com.fincore.cbpcarrierwebservice.ICarrierService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-04T14:48:58.615Z
 * Generated source version: 3.2.1
 * 
 */
public final class ICarrierService_CarrierWcfWebServiceHttp_Client {

    private static final QName SERVICE_NAME = new QName("http://fincore.com/CBPCarrierWebService/", "CarrierService");

    private ICarrierService_CarrierWcfWebServiceHttp_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CarrierService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CarrierService ss = new CarrierService(wsdlURL, SERVICE_NAME);
        ICarrierService port = ss.getCarrierWcfWebServiceHttp();  
        
        {
        System.out.println("Invoking submitWithAttachments...");
        java.lang.String _submitWithAttachments_username = "";
        java.lang.String _submitWithAttachments_password = "";
        com.fincore.cbpcarrierwebservice.entities.ArrayOfFile _submitWithAttachments_files = null;
        com.fincore.cbpcarrierwebservice.entities.SubmitReturnType _submitWithAttachments__return = port.submitWithAttachments(_submitWithAttachments_username, _submitWithAttachments_password, _submitWithAttachments_files);
        System.out.println("submitWithAttachments.result=" + _submitWithAttachments__return);


        }
        {
        System.out.println("Invoking submitFALWithTypedAttachments...");
        java.lang.String _submitFALWithTypedAttachments_username = "";
        java.lang.String _submitFALWithTypedAttachments_password = "";
        com.fincore.cbpcarrierwebservice.entities.ArrayOfTypedFile _submitFALWithTypedAttachments_files = null;
        com.fincore.cbpcarrierwebservice.entities.SubmitReturnType _submitFALWithTypedAttachments__return = port.submitFALWithTypedAttachments(_submitFALWithTypedAttachments_username, _submitFALWithTypedAttachments_password, _submitFALWithTypedAttachments_files);
        System.out.println("submitFALWithTypedAttachments.result=" + _submitFALWithTypedAttachments__return);


        }
        {
        System.out.println("Invoking submitSTTXML...");
        java.lang.String _submitSTTXML_username = "";
        java.lang.String _submitSTTXML_password = "";
        java.lang.String _submitSTTXML_sttXml = "";
        com.fincore.cbpcarrierwebservice.entities.SubmitReturnType _submitSTTXML__return = port.submitSTTXML(_submitSTTXML_username, _submitSTTXML_password, _submitSTTXML_sttXml);
        System.out.println("submitSTTXML.result=" + _submitSTTXML__return);


        }
        {
        System.out.println("Invoking cancel...");
        java.lang.String _cancel_username = "";
        java.lang.String _cancel_password = "";
        java.lang.String _cancel_identifier = "";
        java.lang.String _cancel_reason = "";
        com.fincore.cbpcarrierwebservice.entities.CancelReturnType _cancel__return = port.cancel(_cancel_username, _cancel_password, _cancel_identifier, _cancel_reason);
        System.out.println("cancel.result=" + _cancel__return);


        }
        {
        System.out.println("Invoking version...");
        java.lang.String _version_username = "";
        java.lang.String _version_password = "";
        java.lang.String _version__return = port.version(_version_username, _version_password);
        System.out.println("version.result=" + _version__return);


        }
        {
        System.out.println("Invoking heartbeat...");
        java.lang.String _heartbeat_username = "";
        java.lang.String _heartbeat_password = "";
        java.lang.Boolean _heartbeat__return = port.heartbeat(_heartbeat_username, _heartbeat_password);
        System.out.println("heartbeat.result=" + _heartbeat__return);


        }

        System.exit(0);
    }

}
