package com.fincore.cbpcarrierwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-04T14:48:58.679Z
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://fincore.com/CBPCarrierWebService/", name = "ICarrierService")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.fincore.cbpcarrierwebservice.entities.ObjectFactory.class})
public interface ICarrierService {

    @WebMethod(operationName = "SubmitWithAttachments", action = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitWithAttachments")
    @Action(input = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitWithAttachments", output = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitWithAttachmentsResponse")
    @RequestWrapper(localName = "SubmitWithAttachments", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.SubmitWithAttachments")
    @ResponseWrapper(localName = "SubmitWithAttachmentsResponse", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.SubmitWithAttachmentsResponse")
    @WebResult(name = "SubmitWithAttachmentsResult", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
    public com.fincore.cbpcarrierwebservice.entities.SubmitReturnType submitWithAttachments(
        @WebParam(name = "username", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String password,
        @WebParam(name = "files", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        com.fincore.cbpcarrierwebservice.entities.ArrayOfFile files
    );

    @WebMethod(operationName = "SubmitFALWithTypedAttachments", action = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitFALWithTypedAttachments")
    @Action(input = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitFALWithTypedAttachments", output = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitFALWithTypedAttachmentsResponse")
    @RequestWrapper(localName = "SubmitFALWithTypedAttachments", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.SubmitFALWithTypedAttachments")
    @ResponseWrapper(localName = "SubmitFALWithTypedAttachmentsResponse", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.SubmitFALWithTypedAttachmentsResponse")
    @WebResult(name = "SubmitFALWithTypedAttachmentsResult", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
    public com.fincore.cbpcarrierwebservice.entities.SubmitReturnType submitFALWithTypedAttachments(
        @WebParam(name = "username", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String password,
        @WebParam(name = "files", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        com.fincore.cbpcarrierwebservice.entities.ArrayOfTypedFile files
    );

    @WebMethod(operationName = "SubmitSTTXML", action = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitSTTXML")
    @Action(input = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitSTTXML", output = "http://fincore.com/CBPCarrierWebService/ICarrierService/SubmitSTTXMLResponse")
    @RequestWrapper(localName = "SubmitSTTXML", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.SubmitSTTXML")
    @ResponseWrapper(localName = "SubmitSTTXMLResponse", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.SubmitSTTXMLResponse")
    @WebResult(name = "SubmitSTTXMLResult", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
    public com.fincore.cbpcarrierwebservice.entities.SubmitReturnType submitSTTXML(
        @WebParam(name = "username", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String password,
        @WebParam(name = "stt_xml", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String sttXml
    );

    @WebMethod(operationName = "Cancel", action = "http://fincore.com/CBPCarrierWebService/ICarrierService/Cancel")
    @Action(input = "http://fincore.com/CBPCarrierWebService/ICarrierService/Cancel", output = "http://fincore.com/CBPCarrierWebService/ICarrierService/CancelResponse")
    @RequestWrapper(localName = "Cancel", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.Cancel")
    @ResponseWrapper(localName = "CancelResponse", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.CancelResponse")
    @WebResult(name = "CancelResult", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
    public com.fincore.cbpcarrierwebservice.entities.CancelReturnType cancel(
        @WebParam(name = "username", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String password,
        @WebParam(name = "identifier", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String identifier,
        @WebParam(name = "reason", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String reason
    );

    @WebMethod(operationName = "Version", action = "http://fincore.com/CBPCarrierWebService/ICarrierService/Version")
    @Action(input = "http://fincore.com/CBPCarrierWebService/ICarrierService/Version", output = "http://fincore.com/CBPCarrierWebService/ICarrierService/VersionResponse")
    @RequestWrapper(localName = "Version", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.Version")
    @ResponseWrapper(localName = "VersionResponse", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.VersionResponse")
    @WebResult(name = "VersionResult", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
    public java.lang.String version(
        @WebParam(name = "username", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String password
    );

    @WebMethod(operationName = "Heartbeat", action = "http://fincore.com/CBPCarrierWebService/ICarrierService/Heartbeat")
    @Action(input = "http://fincore.com/CBPCarrierWebService/ICarrierService/Heartbeat", output = "http://fincore.com/CBPCarrierWebService/ICarrierService/HeartbeatResponse")
    @RequestWrapper(localName = "Heartbeat", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.Heartbeat")
    @ResponseWrapper(localName = "HeartbeatResponse", targetNamespace = "http://fincore.com/CBPCarrierWebService/", className = "com.fincore.cbpcarrierwebservice.HeartbeatResponse")
    @WebResult(name = "HeartbeatResult", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
    public java.lang.Boolean heartbeat(
        @WebParam(name = "username", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://fincore.com/CBPCarrierWebService/")
        java.lang.String password
    );
}
