//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fincore.cbp.stt.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CrewAllowances_QNAME = new QName("", "CrewAllowances");
    private final static QName _HomeAddress_QNAME = new QName("", "HomeAddress");
    private final static QName _DepartureTime_QNAME = new QName("", "DepartureTime");
    private final static QName _Gender_QNAME = new QName("", "Gender");
    private final static QName _FirstTimeInUK_QNAME = new QName("", "FirstTimeInUK");
    private final static QName _Cabin_QNAME = new QName("", "Cabin");
    private final static QName _GoodsDetails_QNAME = new QName("", "GoodsDetails");
    private final static QName _PurposeOfVisit_QNAME = new QName("", "PurposeOfVisit");
    private final static QName _Moorings_QNAME = new QName("", "Moorings");
    private final static QName _DepartureDate_QNAME = new QName("", "DepartureDate");
    private final static QName _YearBuilt_QNAME = new QName("", "YearBuilt");
    private final static QName _MetersmaxLength_QNAME = new QName("", "MetersmaxLength");
    private final static QName _CountryOfRegistration_QNAME = new QName("", "CountryOfRegistration");
    private final static QName _ArrivalTime_QNAME = new QName("", "ArrivalTime");
    private final static QName _ManifestType_QNAME = new QName("", "ManifestType");
    private final static QName _OwnerAddress_QNAME = new QName("", "OwnerAddress");
    private final static QName _Make_QNAME = new QName("", "Make");
    private final static QName _Goods_QNAME = new QName("", "Goods");
    private final static QName _HullColour_QNAME = new QName("", "HullColour");
    private final static QName _AddressPostCode_QNAME = new QName("", "AddressPostCode");
    private final static QName _PlaceOfIssue_QNAME = new QName("", "PlaceOfIssue");
    private final static QName _PortOfRegistry_QNAME = new QName("", "PortOfRegistry");
    private final static QName _Person_QNAME = new QName("", "Person");
    private final static QName _CaptainSurname_QNAME = new QName("", "CaptainSurname");
    private final static QName _UK_VAT_Paid_QNAME = new QName("", "UK_VAT_Paid");
    private final static QName _AggregatorName_QNAME = new QName("", "AggregatorName");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _BasedAt_QNAME = new QName("", "BasedAt");
    private final static QName _RepairedOrModified_QNAME = new QName("", "RepairedOrModified");
    private final static QName _GenericMaritime_QNAME = new QName("", "GenericMaritime");
    private final static QName _IMOPort_QNAME = new QName("", "IMOPort");
    private final static QName _GenericAviation_QNAME = new QName("", "GenericAviation");
    private final static QName _SeacraftName_QNAME = new QName("", "SeacraftName");
    private final static QName _PortOfDissembarkation_QNAME = new QName("", "PortOfDissembarkation");
    private final static QName _VoyageEventCode_QNAME = new QName("", "VoyageEventCode");
    private final static QName _CrewPhoneContact_QNAME = new QName("", "CrewPhoneContact");
    private final static QName _PlaceOfBirth_QNAME = new QName("", "PlaceOfBirth");
    private final static QName _WasteRequirements_QNAME = new QName("", "WasteRequirements");
    private final static QName _RegistrationNumber_QNAME = new QName("", "RegistrationNumber");
    private final static QName _CaptainGivenName_QNAME = new QName("", "CaptainGivenName");
    private final static QName _ReasonForVisit_QNAME = new QName("", "ReasonForVisit");
    private final static QName _DutyFreeGoods_QNAME = new QName("", "DutyFreeGoods");
    private final static QName _DocumentNumber_QNAME = new QName("", "DocumentNumber");
    private final static QName _IssuingAuthority_QNAME = new QName("", "IssuingAuthority");
    private final static QName _Nationality_QNAME = new QName("", "Nationality");
    private final static QName _AircraftMake_QNAME = new QName("", "AircraftMake");
    private final static QName _Type_QNAME = new QName("", "Type");
    private final static QName _OwnerSurname_QNAME = new QName("", "OwnerSurname");
    private final static QName _OwnerOrganisation_QNAME = new QName("", "OwnerOrganisation");
    private final static QName _ExpirationDate_QNAME = new QName("", "ExpirationDate");
    private final static QName _ArrivalDate_QNAME = new QName("", "ArrivalDate");
    private final static QName _Model_QNAME = new QName("", "Model");
    private final static QName _ManifestNo_QNAME = new QName("", "ManifestNo");
    private final static QName _IMODate_QNAME = new QName("", "IMODate");
    private final static QName _VesselExportPlaceOfDepartureAtUK_QNAME = new QName("", "VesselExportPlaceOfDepartureAtUK");
    private final static QName _Surname_QNAME = new QName("", "Surname");
    private final static QName _Lat_QNAME = new QName("", "Lat");
    private final static QName _VisitedPorts_QNAME = new QName("", "VisitedPorts");
    private final static QName _PortOfCallArrival_QNAME = new QName("", "PortOfCallArrival");
    private final static QName _FullAddress_QNAME = new QName("", "FullAddress");
    private final static QName _VesselExport_QNAME = new QName("", "VesselExport");
    private final static QName _AircraftLessThan8000Kg_QNAME = new QName("", "AircraftLessThan8000kg");
    private final static QName _FlagStatus_QNAME = new QName("", "FlagStatus");
    private final static QName _BuildLocation_QNAME = new QName("", "BuildLocation");
    private final static QName _IsVisaHolder_QNAME = new QName("", "IsVisaHolder");
    private final static QName _DateOfbirth_QNAME = new QName("", "DateOfbirth");
    private final static QName _GivenName_QNAME = new QName("", "GivenName");
    private final static QName _IsPowered_QNAME = new QName("", "isPowered");
    private final static QName _TelephoneNumber_QNAME = new QName("", "TelephoneNumber");
    private final static QName _ContactNumber_QNAME = new QName("", "ContactNumber");
    private final static QName _ManifestDate_QNAME = new QName("", "ManifestDate");
    private final static QName _SailMarkings_QNAME = new QName("", "SailMarkings");
    private final static QName _TravelDocument_QNAME = new QName("", "TravelDocument");
    private final static QName _PortOfCallDeparture_QNAME = new QName("", "PortOfCallDeparture");
    private final static QName _EBorders_STTDocument_QNAME = new QName("", "eBorders_STTDocument");
    private final static QName _AddressField_QNAME = new QName("", "AddressField");
    private final static QName _CargoDischarged_QNAME = new QName("", "CargoDischarged");
    private final static QName _UKVATPaid_QNAME = new QName("", "UKVATPaid");
    private final static QName _IATA_QNAME = new QName("", "IATA");
    private final static QName _DurationOfStayInUK_QNAME = new QName("", "DurationOfStayInUK");
    private final static QName _IMO_QNAME = new QName("", "IMO");
    private final static QName _RestrictedGoods_QNAME = new QName("", "RestrictedGoods");
    private final static QName _HireCharterDetails_QNAME = new QName("", "HireCharterDetails");
    private final static QName _ISPSLevel_QNAME = new QName("", "ISPSLevel");
    private final static QName _TelephoneNumberType_QNAME = new QName("", "TelephoneNumberType");
    private final static QName _CargoDescription_QNAME = new QName("", "CargoDescription");
    private final static QName _Tonnage_QNAME = new QName("", "Tonnage");
    private final static QName _ManifestTime_QNAME = new QName("", "ManifestTime");
    private final static QName _Long_QNAME = new QName("", "Long");
    private final static QName _GoodsExist_QNAME = new QName("", "GoodsExist");
    private final static QName _AircraftType_QNAME = new QName("", "AircraftType");
    private final static QName _PortOfEmbarkation_QNAME = new QName("", "PortOfEmbarkation");
    private final static QName _HireOrCharter_QNAME = new QName("", "HireOrCharter");
    private final static QName _OwnerGivenName_QNAME = new QName("", "OwnerGivenName");
    private final static QName _AddressCountry_QNAME = new QName("", "AddressCountry");
    private final static QName _TransitPassenger_QNAME = new QName("", "TransitPassenger");
    private final static QName _MMSINumber_QNAME = new QName("", "MMSINumber");
    private final static QName _IsCrew_QNAME = new QName("", "IsCrew");
    private final static QName _CaptainAddress_QNAME = new QName("", "CaptainAddress");
    private final static QName _CallSign_QNAME = new QName("", "CallSign");
    private final static QName _Cancellation_QNAME = new QName("", "Cancellation");
    private final static QName _AircraftModel_QNAME = new QName("", "AircraftModel");
    private final static QName _UNLOCODE_QNAME = new QName("", "UNLOCODE");
    private final static QName _IMONumber_QNAME = new QName("", "IMONumber");
    private final static QName _FreeCirculationInEU_QNAME = new QName("", "FreeCirculationInEU");
    private final static QName _AircraftRegistrationNumber_QNAME = new QName("", "AircraftRegistrationNumber");
    private final static QName _RankRating_QNAME = new QName("", "RankRating");
    private final static QName _ExcessGoods_QNAME = new QName("", "ExcessGoods");
    private final static QName _DocumentType_QNAME = new QName("", "DocumentType");
    private final static QName _CommonSegment_QNAME = new QName("", "CommonSegment");
    private final static QName _VisitingAddress_QNAME = new QName("", "VisitingAddress");
    private final static QName _ICAO_QNAME = new QName("", "ICAO");
    private final static QName _ProhibitedGoods_QNAME = new QName("", "ProhibitedGoods");
    private final static QName _RegistrationCountry_QNAME = new QName("", "RegistrationCountry");
    private final static QName _LatLongPair_QNAME = new QName("", "LatLongPair");
    private final static QName _CargoRemarks_QNAME = new QName("", "CargoRemarks");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fincore.cbp.stt.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link T_CrewAllowances }
     * 
     */
    public T_CrewAllowances createT_CrewAllowances() {
        return new T_CrewAllowances();
    }

    /**
     * Create an instance of {@link T_Address }
     * 
     */
    public T_Address createT_Address() {
        return new T_Address();
    }

    /**
     * Create an instance of {@link T_Port }
     * 
     */
    public T_Port createT_Port() {
        return new T_Port();
    }

    /**
     * Create an instance of {@link T_Person }
     * 
     */
    public T_Person createT_Person() {
        return new T_Person();
    }

    /**
     * Create an instance of {@link T_GenericMaritime }
     * 
     */
    public T_GenericMaritime createT_GenericMaritime() {
        return new T_GenericMaritime();
    }

    /**
     * Create an instance of {@link T_GenericAviation }
     * 
     */
    public T_GenericAviation createT_GenericAviation() {
        return new T_GenericAviation();
    }

    /**
     * Create an instance of {@link T_CrewPhoneContact }
     * 
     */
    public T_CrewPhoneContact createT_CrewPhoneContact() {
        return new T_CrewPhoneContact();
    }

    /**
     * Create an instance of {@link T_DutyFreeGoods }
     * 
     */
    public T_DutyFreeGoods createT_DutyFreeGoods() {
        return new T_DutyFreeGoods();
    }

    /**
     * Create an instance of {@link T_ContactNumber }
     * 
     */
    public T_ContactNumber createT_ContactNumber() {
        return new T_ContactNumber();
    }

    /**
     * Create an instance of {@link T_TravelDocument }
     * 
     */
    public T_TravelDocument createT_TravelDocument() {
        return new T_TravelDocument();
    }

    /**
     * Create an instance of {@link T_EBorders_STTDocument }
     * 
     */
    public T_EBorders_STTDocument createT_EBorders_STTDocument() {
        return new T_EBorders_STTDocument();
    }

    /**
     * Create an instance of {@link T_IMO }
     * 
     */
    public T_IMO createT_IMO() {
        return new T_IMO();
    }

    /**
     * Create an instance of {@link T_RestrictedGoods }
     * 
     */
    public T_RestrictedGoods createT_RestrictedGoods() {
        return new T_RestrictedGoods();
    }

    /**
     * Create an instance of {@link T_ExcessGoods }
     * 
     */
    public T_ExcessGoods createT_ExcessGoods() {
        return new T_ExcessGoods();
    }

    /**
     * Create an instance of {@link T_CommonSegment }
     * 
     */
    public T_CommonSegment createT_CommonSegment() {
        return new T_CommonSegment();
    }

    /**
     * Create an instance of {@link T_ProhibitedGoods }
     * 
     */
    public T_ProhibitedGoods createT_ProhibitedGoods() {
        return new T_ProhibitedGoods();
    }

    /**
     * Create an instance of {@link T_LatLongPair }
     * 
     */
    public T_LatLongPair createT_LatLongPair() {
        return new T_LatLongPair();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_CrewAllowances }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CrewAllowances")
    public JAXBElement<T_CrewAllowances> createCrewAllowances(T_CrewAllowances value) {
        return new JAXBElement<T_CrewAllowances>(_CrewAllowances_QNAME, T_CrewAllowances.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeAddress")
    public JAXBElement<T_Address> createHomeAddress(T_Address value) {
        return new JAXBElement<T_Address>(_HomeAddress_QNAME, T_Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DepartureTime")
    public JAXBElement<XMLGregorianCalendar> createDepartureTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepartureTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Gender }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Gender")
    public JAXBElement<T_Gender> createGender(T_Gender value) {
        return new JAXBElement<T_Gender>(_Gender_QNAME, T_Gender.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstTimeInUK")
    public JAXBElement<Boolean> createFirstTimeInUK(Boolean value) {
        return new JAXBElement<Boolean>(_FirstTimeInUK_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cabin")
    public JAXBElement<String> createCabin(String value) {
        return new JAXBElement<String>(_Cabin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GoodsDetails")
    public JAXBElement<String> createGoodsDetails(String value) {
        return new JAXBElement<String>(_GoodsDetails_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_PurposeOfVisit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PurposeOfVisit")
    public JAXBElement<T_PurposeOfVisit> createPurposeOfVisit(T_PurposeOfVisit value) {
        return new JAXBElement<T_PurposeOfVisit>(_PurposeOfVisit_QNAME, T_PurposeOfVisit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Moorings")
    public JAXBElement<T_Port> createMoorings(T_Port value) {
        return new JAXBElement<T_Port>(_Moorings_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DepartureDate")
    public JAXBElement<XMLGregorianCalendar> createDepartureDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepartureDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YearBuilt")
    public JAXBElement<String> createYearBuilt(String value) {
        return new JAXBElement<String>(_YearBuilt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MetersmaxLength")
    public JAXBElement<String> createMetersmaxLength(String value) {
        return new JAXBElement<String>(_MetersmaxLength_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountryOfRegistration")
    public JAXBElement<String> createCountryOfRegistration(String value) {
        return new JAXBElement<String>(_CountryOfRegistration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrivalTime")
    public JAXBElement<XMLGregorianCalendar> createArrivalTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ArrivalTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ManifestType")
    public JAXBElement<String> createManifestType(String value) {
        return new JAXBElement<String>(_ManifestType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OwnerAddress")
    public JAXBElement<T_Address> createOwnerAddress(T_Address value) {
        return new JAXBElement<T_Address>(_OwnerAddress_QNAME, T_Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Make")
    public JAXBElement<String> createMake(String value) {
        return new JAXBElement<String>(_Make_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Goods")
    public JAXBElement<String> createGoods(String value) {
        return new JAXBElement<String>(_Goods_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HullColour")
    public JAXBElement<String> createHullColour(String value) {
        return new JAXBElement<String>(_HullColour_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressPostCode")
    public JAXBElement<String> createAddressPostCode(String value) {
        return new JAXBElement<String>(_AddressPostCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlaceOfIssue")
    public JAXBElement<String> createPlaceOfIssue(String value) {
        return new JAXBElement<String>(_PlaceOfIssue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PortOfRegistry")
    public JAXBElement<T_Port> createPortOfRegistry(T_Port value) {
        return new JAXBElement<T_Port>(_PortOfRegistry_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Person")
    public JAXBElement<T_Person> createPerson(T_Person value) {
        return new JAXBElement<T_Person>(_Person_QNAME, T_Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CaptainSurname")
    public JAXBElement<String> createCaptainSurname(String value) {
        return new JAXBElement<String>(_CaptainSurname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UK_VAT_Paid")
    public JAXBElement<Boolean> createUK_VAT_Paid(Boolean value) {
        return new JAXBElement<Boolean>(_UK_VAT_Paid_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AggregatorName")
    public JAXBElement<String> createAggregatorName(String value) {
        return new JAXBElement<String>(_AggregatorName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BasedAt")
    public JAXBElement<String> createBasedAt(String value) {
        return new JAXBElement<String>(_BasedAt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RepairedOrModified")
    public JAXBElement<Boolean> createRepairedOrModified(Boolean value) {
        return new JAXBElement<Boolean>(_RepairedOrModified_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_GenericMaritime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericMaritime")
    public JAXBElement<T_GenericMaritime> createGenericMaritime(T_GenericMaritime value) {
        return new JAXBElement<T_GenericMaritime>(_GenericMaritime_QNAME, T_GenericMaritime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMOPort")
    public JAXBElement<T_Port> createIMOPort(T_Port value) {
        return new JAXBElement<T_Port>(_IMOPort_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_GenericAviation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericAviation")
    public JAXBElement<T_GenericAviation> createGenericAviation(T_GenericAviation value) {
        return new JAXBElement<T_GenericAviation>(_GenericAviation_QNAME, T_GenericAviation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SeacraftName")
    public JAXBElement<String> createSeacraftName(String value) {
        return new JAXBElement<String>(_SeacraftName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PortOfDissembarkation")
    public JAXBElement<T_Port> createPortOfDissembarkation(T_Port value) {
        return new JAXBElement<T_Port>(_PortOfDissembarkation_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VoyageEventCode", defaultValue = "DC")
    public JAXBElement<String> createVoyageEventCode(String value) {
        return new JAXBElement<String>(_VoyageEventCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_CrewPhoneContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CrewPhoneContact")
    public JAXBElement<T_CrewPhoneContact> createCrewPhoneContact(T_CrewPhoneContact value) {
        return new JAXBElement<T_CrewPhoneContact>(_CrewPhoneContact_QNAME, T_CrewPhoneContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlaceOfBirth")
    public JAXBElement<String> createPlaceOfBirth(String value) {
        return new JAXBElement<String>(_PlaceOfBirth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WasteRequirements")
    public JAXBElement<String> createWasteRequirements(String value) {
        return new JAXBElement<String>(_WasteRequirements_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegistrationNumber")
    public JAXBElement<String> createRegistrationNumber(String value) {
        return new JAXBElement<String>(_RegistrationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CaptainGivenName")
    public JAXBElement<String> createCaptainGivenName(String value) {
        return new JAXBElement<String>(_CaptainGivenName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_ReasonForVisit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReasonForVisit")
    public JAXBElement<T_ReasonForVisit> createReasonForVisit(T_ReasonForVisit value) {
        return new JAXBElement<T_ReasonForVisit>(_ReasonForVisit_QNAME, T_ReasonForVisit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_DutyFreeGoods }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DutyFreeGoods")
    public JAXBElement<T_DutyFreeGoods> createDutyFreeGoods(T_DutyFreeGoods value) {
        return new JAXBElement<T_DutyFreeGoods>(_DutyFreeGoods_QNAME, T_DutyFreeGoods.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentNumber")
    public JAXBElement<String> createDocumentNumber(String value) {
        return new JAXBElement<String>(_DocumentNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IssuingAuthority")
    public JAXBElement<String> createIssuingAuthority(String value) {
        return new JAXBElement<String>(_IssuingAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Nationality")
    public JAXBElement<String> createNationality(String value) {
        return new JAXBElement<String>(_Nationality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AircraftMake")
    public JAXBElement<String> createAircraftMake(String value) {
        return new JAXBElement<String>(_AircraftMake_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OwnerSurname")
    public JAXBElement<String> createOwnerSurname(String value) {
        return new JAXBElement<String>(_OwnerSurname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OwnerOrganisation")
    public JAXBElement<String> createOwnerOrganisation(String value) {
        return new JAXBElement<String>(_OwnerOrganisation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpirationDate")
    public JAXBElement<XMLGregorianCalendar> createExpirationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ExpirationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrivalDate")
    public JAXBElement<XMLGregorianCalendar> createArrivalDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ArrivalDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Model")
    public JAXBElement<String> createModel(String value) {
        return new JAXBElement<String>(_Model_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ManifestNo")
    public JAXBElement<BigInteger> createManifestNo(BigInteger value) {
        return new JAXBElement<BigInteger>(_ManifestNo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMODate")
    public JAXBElement<XMLGregorianCalendar> createIMODate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IMODate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VesselExportPlaceOfDepartureAtUK")
    public JAXBElement<String> createVesselExportPlaceOfDepartureAtUK(String value) {
        return new JAXBElement<String>(_VesselExportPlaceOfDepartureAtUK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Surname")
    public JAXBElement<String> createSurname(String value) {
        return new JAXBElement<String>(_Surname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lat")
    public JAXBElement<String> createLat(String value) {
        return new JAXBElement<String>(_Lat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VisitedPorts")
    public JAXBElement<T_Port> createVisitedPorts(T_Port value) {
        return new JAXBElement<T_Port>(_VisitedPorts_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PortOfCallArrival")
    public JAXBElement<T_Port> createPortOfCallArrival(T_Port value) {
        return new JAXBElement<T_Port>(_PortOfCallArrival_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FullAddress")
    public JAXBElement<T_Address> createFullAddress(T_Address value) {
        return new JAXBElement<T_Address>(_FullAddress_QNAME, T_Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VesselExport")
    public JAXBElement<Boolean> createVesselExport(Boolean value) {
        return new JAXBElement<Boolean>(_VesselExport_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AircraftLessThan8000kg")
    public JAXBElement<Boolean> createAircraftLessThan8000Kg(Boolean value) {
        return new JAXBElement<Boolean>(_AircraftLessThan8000Kg_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FlagStatus")
    public JAXBElement<String> createFlagStatus(String value) {
        return new JAXBElement<String>(_FlagStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BuildLocation")
    public JAXBElement<T_Port> createBuildLocation(T_Port value) {
        return new JAXBElement<T_Port>(_BuildLocation_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsVisaHolder")
    public JAXBElement<Boolean> createIsVisaHolder(Boolean value) {
        return new JAXBElement<Boolean>(_IsVisaHolder_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateOfbirth")
    public JAXBElement<XMLGregorianCalendar> createDateOfbirth(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateOfbirth_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GivenName")
    public JAXBElement<String> createGivenName(String value) {
        return new JAXBElement<String>(_GivenName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isPowered")
    public JAXBElement<Boolean> createIsPowered(Boolean value) {
        return new JAXBElement<Boolean>(_IsPowered_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TelephoneNumber")
    public JAXBElement<String> createTelephoneNumber(String value) {
        return new JAXBElement<String>(_TelephoneNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_ContactNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ContactNumber")
    public JAXBElement<T_ContactNumber> createContactNumber(T_ContactNumber value) {
        return new JAXBElement<T_ContactNumber>(_ContactNumber_QNAME, T_ContactNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ManifestDate")
    public JAXBElement<XMLGregorianCalendar> createManifestDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ManifestDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SailMarkings")
    public JAXBElement<String> createSailMarkings(String value) {
        return new JAXBElement<String>(_SailMarkings_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_TravelDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TravelDocument")
    public JAXBElement<T_TravelDocument> createTravelDocument(T_TravelDocument value) {
        return new JAXBElement<T_TravelDocument>(_TravelDocument_QNAME, T_TravelDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PortOfCallDeparture")
    public JAXBElement<T_Port> createPortOfCallDeparture(T_Port value) {
        return new JAXBElement<T_Port>(_PortOfCallDeparture_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_EBorders_STTDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eBorders_STTDocument")
    public JAXBElement<T_EBorders_STTDocument> createEBorders_STTDocument(T_EBorders_STTDocument value) {
        return new JAXBElement<T_EBorders_STTDocument>(_EBorders_STTDocument_QNAME, T_EBorders_STTDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressField")
    public JAXBElement<String> createAddressField(String value) {
        return new JAXBElement<String>(_AddressField_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CargoDischarged")
    public JAXBElement<String> createCargoDischarged(String value) {
        return new JAXBElement<String>(_CargoDischarged_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UKVATPaid")
    public JAXBElement<Boolean> createUKVATPaid(Boolean value) {
        return new JAXBElement<Boolean>(_UKVATPaid_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IATA")
    public JAXBElement<String> createIATA(String value) {
        return new JAXBElement<String>(_IATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DurationOfStayInUK")
    public JAXBElement<String> createDurationOfStayInUK(String value) {
        return new JAXBElement<String>(_DurationOfStayInUK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_IMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMO")
    public JAXBElement<T_IMO> createIMO(T_IMO value) {
        return new JAXBElement<T_IMO>(_IMO_QNAME, T_IMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_RestrictedGoods }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RestrictedGoods")
    public JAXBElement<T_RestrictedGoods> createRestrictedGoods(T_RestrictedGoods value) {
        return new JAXBElement<T_RestrictedGoods>(_RestrictedGoods_QNAME, T_RestrictedGoods.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HireCharterDetails")
    public JAXBElement<String> createHireCharterDetails(String value) {
        return new JAXBElement<String>(_HireCharterDetails_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISPSLevel")
    public JAXBElement<BigInteger> createISPSLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_ISPSLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_TelephoneNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TelephoneNumberType")
    public JAXBElement<T_TelephoneNumberType> createTelephoneNumberType(T_TelephoneNumberType value) {
        return new JAXBElement<T_TelephoneNumberType>(_TelephoneNumberType_QNAME, T_TelephoneNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CargoDescription")
    public JAXBElement<String> createCargoDescription(String value) {
        return new JAXBElement<String>(_CargoDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tonnage")
    public JAXBElement<String> createTonnage(String value) {
        return new JAXBElement<String>(_Tonnage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ManifestTime")
    public JAXBElement<XMLGregorianCalendar> createManifestTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ManifestTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Long")
    public JAXBElement<String> createLong(String value) {
        return new JAXBElement<String>(_Long_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GoodsExist")
    public JAXBElement<Boolean> createGoodsExist(Boolean value) {
        return new JAXBElement<Boolean>(_GoodsExist_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AircraftType")
    public JAXBElement<String> createAircraftType(String value) {
        return new JAXBElement<String>(_AircraftType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PortOfEmbarkation")
    public JAXBElement<T_Port> createPortOfEmbarkation(T_Port value) {
        return new JAXBElement<T_Port>(_PortOfEmbarkation_QNAME, T_Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_HireOrCharter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HireOrCharter")
    public JAXBElement<T_HireOrCharter> createHireOrCharter(T_HireOrCharter value) {
        return new JAXBElement<T_HireOrCharter>(_HireOrCharter_QNAME, T_HireOrCharter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OwnerGivenName")
    public JAXBElement<String> createOwnerGivenName(String value) {
        return new JAXBElement<String>(_OwnerGivenName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressCountry")
    public JAXBElement<String> createAddressCountry(String value) {
        return new JAXBElement<String>(_AddressCountry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransitPassenger")
    public JAXBElement<Boolean> createTransitPassenger(Boolean value) {
        return new JAXBElement<Boolean>(_TransitPassenger_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MMSINumber")
    public JAXBElement<String> createMMSINumber(String value) {
        return new JAXBElement<String>(_MMSINumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsCrew")
    public JAXBElement<Boolean> createIsCrew(Boolean value) {
        return new JAXBElement<Boolean>(_IsCrew_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CaptainAddress")
    public JAXBElement<T_Address> createCaptainAddress(T_Address value) {
        return new JAXBElement<T_Address>(_CaptainAddress_QNAME, T_Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CallSign")
    public JAXBElement<String> createCallSign(String value) {
        return new JAXBElement<String>(_CallSign_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cancellation")
    public JAXBElement<String> createCancellation(String value) {
        return new JAXBElement<String>(_Cancellation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AircraftModel")
    public JAXBElement<String> createAircraftModel(String value) {
        return new JAXBElement<String>(_AircraftModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UNLOCODE")
    public JAXBElement<String> createUNLOCODE(String value) {
        return new JAXBElement<String>(_UNLOCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMONumber")
    public JAXBElement<String> createIMONumber(String value) {
        return new JAXBElement<String>(_IMONumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FreeCirculationInEU")
    public JAXBElement<Boolean> createFreeCirculationInEU(Boolean value) {
        return new JAXBElement<Boolean>(_FreeCirculationInEU_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AircraftRegistrationNumber")
    public JAXBElement<String> createAircraftRegistrationNumber(String value) {
        return new JAXBElement<String>(_AircraftRegistrationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RankRating")
    public JAXBElement<String> createRankRating(String value) {
        return new JAXBElement<String>(_RankRating_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_ExcessGoods }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExcessGoods")
    public JAXBElement<T_ExcessGoods> createExcessGoods(T_ExcessGoods value) {
        return new JAXBElement<T_ExcessGoods>(_ExcessGoods_QNAME, T_ExcessGoods.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentType")
    public JAXBElement<T_DocumentType> createDocumentType(T_DocumentType value) {
        return new JAXBElement<T_DocumentType>(_DocumentType_QNAME, T_DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_CommonSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CommonSegment")
    public JAXBElement<T_CommonSegment> createCommonSegment(T_CommonSegment value) {
        return new JAXBElement<T_CommonSegment>(_CommonSegment_QNAME, T_CommonSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VisitingAddress")
    public JAXBElement<T_Address> createVisitingAddress(T_Address value) {
        return new JAXBElement<T_Address>(_VisitingAddress_QNAME, T_Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ICAO")
    public JAXBElement<String> createICAO(String value) {
        return new JAXBElement<String>(_ICAO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_ProhibitedGoods }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProhibitedGoods")
    public JAXBElement<T_ProhibitedGoods> createProhibitedGoods(T_ProhibitedGoods value) {
        return new JAXBElement<T_ProhibitedGoods>(_ProhibitedGoods_QNAME, T_ProhibitedGoods.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegistrationCountry")
    public JAXBElement<String> createRegistrationCountry(String value) {
        return new JAXBElement<String>(_RegistrationCountry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link T_LatLongPair }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LatLongPair")
    public JAXBElement<T_LatLongPair> createLatLongPair(T_LatLongPair value) {
        return new JAXBElement<T_LatLongPair>(_LatLongPair_QNAME, T_LatLongPair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CargoRemarks")
    public JAXBElement<String> createCargoRemarks(String value) {
        return new JAXBElement<String>(_CargoRemarks_QNAME, String.class, null, value);
    }

}
