//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_ContactNumber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_ContactNumber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TelephoneNumber"/>
 *         &lt;element ref="{}TelephoneNumberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_ContactNumber", propOrder = {
    "telephoneNumber",
    "telephoneNumberType"
})
public class T_ContactNumber {

    @XmlElement(name = "TelephoneNumber", required = true)
    protected String telephoneNumber;
    @XmlElement(name = "TelephoneNumberType")
    @XmlSchemaType(name = "string")
    protected T_TelephoneNumberType telephoneNumberType;

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumber(String value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the telephoneNumberType property.
     * 
     * @return
     *     possible object is
     *     {@link T_TelephoneNumberType }
     *     
     */
    public T_TelephoneNumberType getTelephoneNumberType() {
        return telephoneNumberType;
    }

    /**
     * Sets the value of the telephoneNumberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_TelephoneNumberType }
     *     
     */
    public void setTelephoneNumberType(T_TelephoneNumberType value) {
        this.telephoneNumberType = value;
    }

}
