//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for T_CommonSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_CommonSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}VoyageEventCode"/>
 *         &lt;element ref="{}PortOfCallArrival"/>
 *         &lt;element ref="{}PortOfCallDeparture"/>
 *         &lt;element ref="{}OwnerOrganisation" minOccurs="0"/>
 *         &lt;element ref="{}OwnerSurname" minOccurs="0"/>
 *         &lt;element ref="{}OwnerGivenName" minOccurs="0"/>
 *         &lt;element ref="{}OwnerAddress" minOccurs="0"/>
 *         &lt;element ref="{}CaptainSurname" minOccurs="0"/>
 *         &lt;element ref="{}CaptainGivenName" minOccurs="0"/>
 *         &lt;element ref="{}CaptainAddress" minOccurs="0"/>
 *         &lt;element ref="{}ProhibitedGoods" minOccurs="0"/>
 *         &lt;element ref="{}RestrictedGoods" minOccurs="0"/>
 *         &lt;element ref="{}DutyFreeGoods" minOccurs="0"/>
 *         &lt;element ref="{}ExcessGoods" minOccurs="0"/>
 *         &lt;element ref="{}VesselExport" minOccurs="0"/>
 *         &lt;element ref="{}VesselExportPlaceOfDepartureAtUK" minOccurs="0"/>
 *         &lt;element ref="{}Person" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}DepartureDate"/>
 *         &lt;element ref="{}DepartureTime"/>
 *         &lt;element ref="{}ArrivalDate"/>
 *         &lt;element ref="{}ArrivalTime"/>
 *         &lt;element ref="{}ManifestType"/>
 *         &lt;element ref="{}ManifestNo"/>
 *         &lt;element ref="{}ManifestDate"/>
 *         &lt;element ref="{}ManifestTime"/>
 *         &lt;element ref="{}AggregatorName" minOccurs="0"/>
 *         &lt;element ref="{}Cancellation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_CommonSegment", propOrder = {
    "voyageEventCode",
    "portOfCallArrival",
    "portOfCallDeparture",
    "ownerOrganisation",
    "ownerSurname",
    "ownerGivenName",
    "ownerAddress",
    "captainSurname",
    "captainGivenName",
    "captainAddress",
    "prohibitedGoods",
    "restrictedGoods",
    "dutyFreeGoods",
    "excessGoods",
    "vesselExport",
    "vesselExportPlaceOfDepartureAtUK",
    "person",
    "departureDate",
    "departureTime",
    "arrivalDate",
    "arrivalTime",
    "manifestType",
    "manifestNo",
    "manifestDate",
    "manifestTime",
    "aggregatorName",
    "cancellation"
})
public class T_CommonSegment {

    @XmlElement(name = "VoyageEventCode", required = true, defaultValue = "DC")
    protected String voyageEventCode;
    @XmlElement(name = "PortOfCallArrival", required = true)
    protected T_Port portOfCallArrival;
    @XmlElement(name = "PortOfCallDeparture", required = true)
    protected T_Port portOfCallDeparture;
    @XmlElement(name = "OwnerOrganisation")
    protected String ownerOrganisation;
    @XmlElement(name = "OwnerSurname")
    protected String ownerSurname;
    @XmlElement(name = "OwnerGivenName")
    protected String ownerGivenName;
    @XmlElement(name = "OwnerAddress")
    protected T_Address ownerAddress;
    @XmlElement(name = "CaptainSurname")
    protected String captainSurname;
    @XmlElement(name = "CaptainGivenName")
    protected String captainGivenName;
    @XmlElement(name = "CaptainAddress")
    protected T_Address captainAddress;
    @XmlElement(name = "ProhibitedGoods")
    protected T_ProhibitedGoods prohibitedGoods;
    @XmlElement(name = "RestrictedGoods")
    protected T_RestrictedGoods restrictedGoods;
    @XmlElement(name = "DutyFreeGoods")
    protected T_DutyFreeGoods dutyFreeGoods;
    @XmlElement(name = "ExcessGoods")
    protected T_ExcessGoods excessGoods;
    @XmlElement(name = "VesselExport")
    protected Boolean vesselExport;
    @XmlElement(name = "VesselExportPlaceOfDepartureAtUK")
    protected String vesselExportPlaceOfDepartureAtUK;
    @XmlElement(name = "Person")
    protected List<T_Person> person;
    @XmlElement(name = "DepartureDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar departureDate;
    @XmlElement(name = "DepartureTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar departureTime;
    @XmlElement(name = "ArrivalDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar arrivalDate;
    @XmlElement(name = "ArrivalTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar arrivalTime;
    @XmlElement(name = "ManifestType", required = true)
    protected String manifestType;
    @XmlElement(name = "ManifestNo", required = true)
    protected BigInteger manifestNo;
    @XmlElement(name = "ManifestDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar manifestDate;
    @XmlElement(name = "ManifestTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar manifestTime;
    @XmlElement(name = "AggregatorName")
    protected String aggregatorName;
    @XmlElement(name = "Cancellation")
    protected String cancellation;

    /**
     * A code indicating the type of voyage. Valid values are: DC - Departure Confirmation, DE - Departure Exception
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoyageEventCode() {
        return voyageEventCode;
    }

    /**
     * Sets the value of the voyageEventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyageEventCode(String value) {
        this.voyageEventCode = value;
    }

    /**
     * Gets the value of the portOfCallArrival property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getPortOfCallArrival() {
        return portOfCallArrival;
    }

    /**
     * Sets the value of the portOfCallArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setPortOfCallArrival(T_Port value) {
        this.portOfCallArrival = value;
    }

    /**
     * Gets the value of the portOfCallDeparture property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getPortOfCallDeparture() {
        return portOfCallDeparture;
    }

    /**
     * Sets the value of the portOfCallDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setPortOfCallDeparture(T_Port value) {
        this.portOfCallDeparture = value;
    }

    /**
     * Gets the value of the ownerOrganisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerOrganisation() {
        return ownerOrganisation;
    }

    /**
     * Sets the value of the ownerOrganisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerOrganisation(String value) {
        this.ownerOrganisation = value;
    }

    /**
     * Gets the value of the ownerSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerSurname() {
        return ownerSurname;
    }

    /**
     * Sets the value of the ownerSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerSurname(String value) {
        this.ownerSurname = value;
    }

    /**
     * Gets the value of the ownerGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerGivenName() {
        return ownerGivenName;
    }

    /**
     * Sets the value of the ownerGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerGivenName(String value) {
        this.ownerGivenName = value;
    }

    /**
     * Gets the value of the ownerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link T_Address }
     *     
     */
    public T_Address getOwnerAddress() {
        return ownerAddress;
    }

    /**
     * Sets the value of the ownerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Address }
     *     
     */
    public void setOwnerAddress(T_Address value) {
        this.ownerAddress = value;
    }

    /**
     * Gets the value of the captainSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptainSurname() {
        return captainSurname;
    }

    /**
     * Sets the value of the captainSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptainSurname(String value) {
        this.captainSurname = value;
    }

    /**
     * Gets the value of the captainGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptainGivenName() {
        return captainGivenName;
    }

    /**
     * Sets the value of the captainGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptainGivenName(String value) {
        this.captainGivenName = value;
    }

    /**
     * Gets the value of the captainAddress property.
     * 
     * @return
     *     possible object is
     *     {@link T_Address }
     *     
     */
    public T_Address getCaptainAddress() {
        return captainAddress;
    }

    /**
     * Sets the value of the captainAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Address }
     *     
     */
    public void setCaptainAddress(T_Address value) {
        this.captainAddress = value;
    }

    /**
     * Gets the value of the prohibitedGoods property.
     * 
     * @return
     *     possible object is
     *     {@link T_ProhibitedGoods }
     *     
     */
    public T_ProhibitedGoods getProhibitedGoods() {
        return prohibitedGoods;
    }

    /**
     * Sets the value of the prohibitedGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_ProhibitedGoods }
     *     
     */
    public void setProhibitedGoods(T_ProhibitedGoods value) {
        this.prohibitedGoods = value;
    }

    /**
     * Gets the value of the restrictedGoods property.
     * 
     * @return
     *     possible object is
     *     {@link T_RestrictedGoods }
     *     
     */
    public T_RestrictedGoods getRestrictedGoods() {
        return restrictedGoods;
    }

    /**
     * Sets the value of the restrictedGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_RestrictedGoods }
     *     
     */
    public void setRestrictedGoods(T_RestrictedGoods value) {
        this.restrictedGoods = value;
    }

    /**
     * Gets the value of the dutyFreeGoods property.
     * 
     * @return
     *     possible object is
     *     {@link T_DutyFreeGoods }
     *     
     */
    public T_DutyFreeGoods getDutyFreeGoods() {
        return dutyFreeGoods;
    }

    /**
     * Sets the value of the dutyFreeGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_DutyFreeGoods }
     *     
     */
    public void setDutyFreeGoods(T_DutyFreeGoods value) {
        this.dutyFreeGoods = value;
    }

    /**
     * Gets the value of the excessGoods property.
     * 
     * @return
     *     possible object is
     *     {@link T_ExcessGoods }
     *     
     */
    public T_ExcessGoods getExcessGoods() {
        return excessGoods;
    }

    /**
     * Sets the value of the excessGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_ExcessGoods }
     *     
     */
    public void setExcessGoods(T_ExcessGoods value) {
        this.excessGoods = value;
    }

    /**
     * Gets the value of the vesselExport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVesselExport() {
        return vesselExport;
    }

    /**
     * Sets the value of the vesselExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVesselExport(Boolean value) {
        this.vesselExport = value;
    }

    /**
     * Gets the value of the vesselExportPlaceOfDepartureAtUK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselExportPlaceOfDepartureAtUK() {
        return vesselExportPlaceOfDepartureAtUK;
    }

    /**
     * Sets the value of the vesselExportPlaceOfDepartureAtUK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselExportPlaceOfDepartureAtUK(String value) {
        this.vesselExportPlaceOfDepartureAtUK = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_Person }
     * 
     * 
     */
    public List<T_Person> getPerson() {
        if (person == null) {
            person = new ArrayList<T_Person>();
        }
        return this.person;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureTime(XMLGregorianCalendar value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalDate(XMLGregorianCalendar value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalTime(XMLGregorianCalendar value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the manifestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManifestType() {
        return manifestType;
    }

    /**
     * Sets the value of the manifestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManifestType(String value) {
        this.manifestType = value;
    }

    /**
     * Gets the value of the manifestNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getManifestNo() {
        return manifestNo;
    }

    /**
     * Sets the value of the manifestNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setManifestNo(BigInteger value) {
        this.manifestNo = value;
    }

    /**
     * Gets the value of the manifestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getManifestDate() {
        return manifestDate;
    }

    /**
     * Sets the value of the manifestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setManifestDate(XMLGregorianCalendar value) {
        this.manifestDate = value;
    }

    /**
     * Gets the value of the manifestTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getManifestTime() {
        return manifestTime;
    }

    /**
     * Sets the value of the manifestTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setManifestTime(XMLGregorianCalendar value) {
        this.manifestTime = value;
    }

    /**
     * Gets the value of the aggregatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregatorName() {
        return aggregatorName;
    }

    /**
     * Sets the value of the aggregatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregatorName(String value) {
        this.aggregatorName = value;
    }

    /**
     * Gets the value of the cancellation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellation() {
        return cancellation;
    }

    /**
     * Sets the value of the cancellation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellation(String value) {
        this.cancellation = value;
    }

}
