//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_eBorders_STTDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_eBorders_STTDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CommonSegment"/>
 *         &lt;choice>
 *           &lt;element ref="{}GenericAviation"/>
 *           &lt;element ref="{}GenericMaritime"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="SchemaVersion" use="required" type="{}AT_1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_eBorders_STTDocument", propOrder = {
    "commonSegment",
    "genericAviation",
    "genericMaritime"
})
public class T_EBorders_STTDocument {

    @XmlElement(name = "CommonSegment", required = true)
    protected T_CommonSegment commonSegment;
    @XmlElement(name = "GenericAviation")
    protected T_GenericAviation genericAviation;
    @XmlElement(name = "GenericMaritime")
    protected T_GenericMaritime genericMaritime;
    @XmlAttribute(name = "SchemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the commonSegment property.
     * 
     * @return
     *     possible object is
     *     {@link T_CommonSegment }
     *     
     */
    public T_CommonSegment getCommonSegment() {
        return commonSegment;
    }

    /**
     * Sets the value of the commonSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_CommonSegment }
     *     
     */
    public void setCommonSegment(T_CommonSegment value) {
        this.commonSegment = value;
    }

    /**
     * Gets the value of the genericAviation property.
     * 
     * @return
     *     possible object is
     *     {@link T_GenericAviation }
     *     
     */
    public T_GenericAviation getGenericAviation() {
        return genericAviation;
    }

    /**
     * Sets the value of the genericAviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_GenericAviation }
     *     
     */
    public void setGenericAviation(T_GenericAviation value) {
        this.genericAviation = value;
    }

    /**
     * Gets the value of the genericMaritime property.
     * 
     * @return
     *     possible object is
     *     {@link T_GenericMaritime }
     *     
     */
    public T_GenericMaritime getGenericMaritime() {
        return genericMaritime;
    }

    /**
     * Sets the value of the genericMaritime property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_GenericMaritime }
     *     
     */
    public void setGenericMaritime(T_GenericMaritime value) {
        this.genericMaritime = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

}
