//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_GenericAviation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_GenericAviation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AircraftRegistrationNumber"/>
 *         &lt;element ref="{}CountryOfRegistration" minOccurs="0"/>
 *         &lt;element ref="{}AircraftType" minOccurs="0"/>
 *         &lt;element ref="{}AircraftMake" minOccurs="0"/>
 *         &lt;element ref="{}AircraftModel" minOccurs="0"/>
 *         &lt;element ref="{}BasedAt" minOccurs="0"/>
 *         &lt;element ref="{}CrewPhoneContact" maxOccurs="3" minOccurs="0"/>
 *         &lt;element ref="{}ReasonForVisit" minOccurs="0"/>
 *         &lt;element ref="{}FreeCirculationInEU" minOccurs="0"/>
 *         &lt;element ref="{}AircraftLessThan8000kg" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_GenericAviation", propOrder = {
    "aircraftRegistrationNumber",
    "countryOfRegistration",
    "aircraftType",
    "aircraftMake",
    "aircraftModel",
    "basedAt",
    "crewPhoneContact",
    "reasonForVisit",
    "freeCirculationInEU",
    "aircraftLessThan8000Kg"
})
public class T_GenericAviation {

    @XmlElement(name = "AircraftRegistrationNumber", required = true)
    protected String aircraftRegistrationNumber;
    @XmlElement(name = "CountryOfRegistration")
    protected String countryOfRegistration;
    @XmlElement(name = "AircraftType")
    protected String aircraftType;
    @XmlElement(name = "AircraftMake")
    protected String aircraftMake;
    @XmlElement(name = "AircraftModel")
    protected String aircraftModel;
    @XmlElement(name = "BasedAt")
    protected String basedAt;
    @XmlElement(name = "CrewPhoneContact")
    protected List<T_CrewPhoneContact> crewPhoneContact;
    @XmlElement(name = "ReasonForVisit")
    @XmlSchemaType(name = "string")
    protected T_ReasonForVisit reasonForVisit;
    @XmlElement(name = "FreeCirculationInEU")
    protected Boolean freeCirculationInEU;
    @XmlElement(name = "AircraftLessThan8000kg")
    protected Boolean aircraftLessThan8000Kg;

    /**
     * Gets the value of the aircraftRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftRegistrationNumber() {
        return aircraftRegistrationNumber;
    }

    /**
     * Sets the value of the aircraftRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftRegistrationNumber(String value) {
        this.aircraftRegistrationNumber = value;
    }

    /**
     * Gets the value of the countryOfRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfRegistration() {
        return countryOfRegistration;
    }

    /**
     * Sets the value of the countryOfRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfRegistration(String value) {
        this.countryOfRegistration = value;
    }

    /**
     * Gets the value of the aircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftType() {
        return aircraftType;
    }

    /**
     * Sets the value of the aircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftType(String value) {
        this.aircraftType = value;
    }

    /**
     * Gets the value of the aircraftMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftMake() {
        return aircraftMake;
    }

    /**
     * Sets the value of the aircraftMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftMake(String value) {
        this.aircraftMake = value;
    }

    /**
     * Gets the value of the aircraftModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftModel() {
        return aircraftModel;
    }

    /**
     * Sets the value of the aircraftModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftModel(String value) {
        this.aircraftModel = value;
    }

    /**
     * Gets the value of the basedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasedAt() {
        return basedAt;
    }

    /**
     * Sets the value of the basedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasedAt(String value) {
        this.basedAt = value;
    }

    /**
     * Gets the value of the crewPhoneContact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crewPhoneContact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrewPhoneContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_CrewPhoneContact }
     * 
     * 
     */
    public List<T_CrewPhoneContact> getCrewPhoneContact() {
        if (crewPhoneContact == null) {
            crewPhoneContact = new ArrayList<T_CrewPhoneContact>();
        }
        return this.crewPhoneContact;
    }

    /**
     * Gets the value of the reasonForVisit property.
     * 
     * @return
     *     possible object is
     *     {@link T_ReasonForVisit }
     *     
     */
    public T_ReasonForVisit getReasonForVisit() {
        return reasonForVisit;
    }

    /**
     * Sets the value of the reasonForVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_ReasonForVisit }
     *     
     */
    public void setReasonForVisit(T_ReasonForVisit value) {
        this.reasonForVisit = value;
    }

    /**
     * Gets the value of the freeCirculationInEU property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeCirculationInEU() {
        return freeCirculationInEU;
    }

    /**
     * Sets the value of the freeCirculationInEU property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeCirculationInEU(Boolean value) {
        this.freeCirculationInEU = value;
    }

    /**
     * Gets the value of the aircraftLessThan8000Kg property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAircraftLessThan8000Kg() {
        return aircraftLessThan8000Kg;
    }

    /**
     * Sets the value of the aircraftLessThan8000Kg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAircraftLessThan8000Kg(Boolean value) {
        this.aircraftLessThan8000Kg = value;
    }

}
