//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_GenericMaritime complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_GenericMaritime">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SeacraftName"/>
 *         &lt;element ref="{}isPowered" minOccurs="0"/>
 *         &lt;element ref="{}Make" minOccurs="0"/>
 *         &lt;element ref="{}Model" minOccurs="0"/>
 *         &lt;element ref="{}Type" minOccurs="0"/>
 *         &lt;element ref="{}FlagStatus" minOccurs="0"/>
 *         &lt;element ref="{}YearBuilt" minOccurs="0"/>
 *         &lt;element ref="{}RegistrationNumber" minOccurs="0"/>
 *         &lt;element ref="{}PortOfRegistry" minOccurs="0"/>
 *         &lt;element ref="{}IMO" minOccurs="0"/>
 *         &lt;element ref="{}MMSINumber" minOccurs="0"/>
 *         &lt;element ref="{}RegistrationCountry" minOccurs="0"/>
 *         &lt;element ref="{}CallSign" minOccurs="0"/>
 *         &lt;element ref="{}SailMarkings" minOccurs="0"/>
 *         &lt;element ref="{}HullColour" minOccurs="0"/>
 *         &lt;element ref="{}MetersmaxLength" minOccurs="0"/>
 *         &lt;element ref="{}Tonnage" minOccurs="0"/>
 *         &lt;element ref="{}Moorings" minOccurs="0"/>
 *         &lt;element ref="{}HireOrCharter" minOccurs="0"/>
 *         &lt;element ref="{}Nationality" minOccurs="0"/>
 *         &lt;element ref="{}HireCharterDetails" minOccurs="0"/>
 *         &lt;element ref="{}BuildLocation" minOccurs="0"/>
 *         &lt;element ref="{}WasteRequirements" minOccurs="0"/>
 *         &lt;element ref="{}CargoDescription" minOccurs="0"/>
 *         &lt;element ref="{}CargoDischarged" minOccurs="0"/>
 *         &lt;element ref="{}CargoRemarks" minOccurs="0"/>
 *         &lt;element ref="{}ISPSLevel" minOccurs="0"/>
 *         &lt;element ref="{}FirstTimeInUK" minOccurs="0"/>
 *         &lt;element ref="{}RepairedOrModified" minOccurs="0"/>
 *         &lt;element ref="{}VisitedPorts" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}UKVATPaid" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_GenericMaritime", propOrder = {
    "seacraftName",
    "isPowered",
    "make",
    "model",
    "type",
    "flagStatus",
    "yearBuilt",
    "registrationNumber",
    "portOfRegistry",
    "imo",
    "mmsiNumber",
    "registrationCountry",
    "callSign",
    "sailMarkings",
    "hullColour",
    "metersmaxLength",
    "tonnage",
    "moorings",
    "hireOrCharter",
    "nationality",
    "hireCharterDetails",
    "buildLocation",
    "wasteRequirements",
    "cargoDescription",
    "cargoDischarged",
    "cargoRemarks",
    "ispsLevel",
    "firstTimeInUK",
    "repairedOrModified",
    "visitedPorts",
    "ukvatPaid"
})
public class T_GenericMaritime {

    @XmlElement(name = "SeacraftName", required = true)
    protected String seacraftName;
    protected Boolean isPowered;
    @XmlElement(name = "Make")
    protected String make;
    @XmlElement(name = "Model")
    protected String model;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "FlagStatus")
    protected String flagStatus;
    @XmlElement(name = "YearBuilt")
    protected String yearBuilt;
    @XmlElement(name = "RegistrationNumber")
    protected String registrationNumber;
    @XmlElement(name = "PortOfRegistry")
    protected T_Port portOfRegistry;
    @XmlElement(name = "IMO")
    protected T_IMO imo;
    @XmlElement(name = "MMSINumber")
    protected String mmsiNumber;
    @XmlElement(name = "RegistrationCountry")
    protected String registrationCountry;
    @XmlElement(name = "CallSign")
    protected String callSign;
    @XmlElement(name = "SailMarkings")
    protected String sailMarkings;
    @XmlElement(name = "HullColour")
    protected String hullColour;
    @XmlElement(name = "MetersmaxLength")
    protected String metersmaxLength;
    @XmlElement(name = "Tonnage")
    protected String tonnage;
    @XmlElement(name = "Moorings")
    protected T_Port moorings;
    @XmlElement(name = "HireOrCharter")
    @XmlSchemaType(name = "string")
    protected T_HireOrCharter hireOrCharter;
    @XmlElement(name = "Nationality")
    protected String nationality;
    @XmlElement(name = "HireCharterDetails")
    protected String hireCharterDetails;
    @XmlElement(name = "BuildLocation")
    protected T_Port buildLocation;
    @XmlElement(name = "WasteRequirements")
    protected String wasteRequirements;
    @XmlElement(name = "CargoDescription")
    protected String cargoDescription;
    @XmlElement(name = "CargoDischarged")
    protected String cargoDischarged;
    @XmlElement(name = "CargoRemarks")
    protected String cargoRemarks;
    @XmlElement(name = "ISPSLevel")
    protected BigInteger ispsLevel;
    @XmlElement(name = "FirstTimeInUK")
    protected Boolean firstTimeInUK;
    @XmlElement(name = "RepairedOrModified")
    protected Boolean repairedOrModified;
    @XmlElement(name = "VisitedPorts")
    protected List<T_Port> visitedPorts;
    @XmlElement(name = "UKVATPaid")
    protected Boolean ukvatPaid;

    /**
     * Gets the value of the seacraftName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeacraftName() {
        return seacraftName;
    }

    /**
     * Sets the value of the seacraftName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeacraftName(String value) {
        this.seacraftName = value;
    }

    /**
     * Gets the value of the isPowered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPowered() {
        return isPowered;
    }

    /**
     * Sets the value of the isPowered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPowered(Boolean value) {
        this.isPowered = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the flagStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagStatus() {
        return flagStatus;
    }

    /**
     * Sets the value of the flagStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagStatus(String value) {
        this.flagStatus = value;
    }

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearBuilt(String value) {
        this.yearBuilt = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the portOfRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getPortOfRegistry() {
        return portOfRegistry;
    }

    /**
     * Sets the value of the portOfRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setPortOfRegistry(T_Port value) {
        this.portOfRegistry = value;
    }

    /**
     * Gets the value of the imo property.
     * 
     * @return
     *     possible object is
     *     {@link T_IMO }
     *     
     */
    public T_IMO getIMO() {
        return imo;
    }

    /**
     * Sets the value of the imo property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_IMO }
     *     
     */
    public void setIMO(T_IMO value) {
        this.imo = value;
    }

    /**
     * Gets the value of the mmsiNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMMSINumber() {
        return mmsiNumber;
    }

    /**
     * Sets the value of the mmsiNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMMSINumber(String value) {
        this.mmsiNumber = value;
    }

    /**
     * Gets the value of the registrationCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationCountry() {
        return registrationCountry;
    }

    /**
     * Sets the value of the registrationCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationCountry(String value) {
        this.registrationCountry = value;
    }

    /**
     * Gets the value of the callSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSign() {
        return callSign;
    }

    /**
     * Sets the value of the callSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSign(String value) {
        this.callSign = value;
    }

    /**
     * Gets the value of the sailMarkings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSailMarkings() {
        return sailMarkings;
    }

    /**
     * Sets the value of the sailMarkings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSailMarkings(String value) {
        this.sailMarkings = value;
    }

    /**
     * Gets the value of the hullColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHullColour() {
        return hullColour;
    }

    /**
     * Sets the value of the hullColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHullColour(String value) {
        this.hullColour = value;
    }

    /**
     * Gets the value of the metersmaxLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetersmaxLength() {
        return metersmaxLength;
    }

    /**
     * Sets the value of the metersmaxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetersmaxLength(String value) {
        this.metersmaxLength = value;
    }

    /**
     * Gets the value of the tonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTonnage() {
        return tonnage;
    }

    /**
     * Sets the value of the tonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTonnage(String value) {
        this.tonnage = value;
    }

    /**
     * Gets the value of the moorings property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getMoorings() {
        return moorings;
    }

    /**
     * Sets the value of the moorings property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setMoorings(T_Port value) {
        this.moorings = value;
    }

    /**
     * Gets the value of the hireOrCharter property.
     * 
     * @return
     *     possible object is
     *     {@link T_HireOrCharter }
     *     
     */
    public T_HireOrCharter getHireOrCharter() {
        return hireOrCharter;
    }

    /**
     * Sets the value of the hireOrCharter property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_HireOrCharter }
     *     
     */
    public void setHireOrCharter(T_HireOrCharter value) {
        this.hireOrCharter = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the hireCharterDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHireCharterDetails() {
        return hireCharterDetails;
    }

    /**
     * Sets the value of the hireCharterDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHireCharterDetails(String value) {
        this.hireCharterDetails = value;
    }

    /**
     * Gets the value of the buildLocation property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getBuildLocation() {
        return buildLocation;
    }

    /**
     * Sets the value of the buildLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setBuildLocation(T_Port value) {
        this.buildLocation = value;
    }

    /**
     * Gets the value of the wasteRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWasteRequirements() {
        return wasteRequirements;
    }

    /**
     * Sets the value of the wasteRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWasteRequirements(String value) {
        this.wasteRequirements = value;
    }

    /**
     * Gets the value of the cargoDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoDescription() {
        return cargoDescription;
    }

    /**
     * Sets the value of the cargoDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoDescription(String value) {
        this.cargoDescription = value;
    }

    /**
     * Gets the value of the cargoDischarged property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoDischarged() {
        return cargoDischarged;
    }

    /**
     * Sets the value of the cargoDischarged property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoDischarged(String value) {
        this.cargoDischarged = value;
    }

    /**
     * Gets the value of the cargoRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoRemarks() {
        return cargoRemarks;
    }

    /**
     * Sets the value of the cargoRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoRemarks(String value) {
        this.cargoRemarks = value;
    }

    /**
     * Gets the value of the ispsLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getISPSLevel() {
        return ispsLevel;
    }

    /**
     * Sets the value of the ispsLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setISPSLevel(BigInteger value) {
        this.ispsLevel = value;
    }

    /**
     * Gets the value of the firstTimeInUK property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFirstTimeInUK() {
        return firstTimeInUK;
    }

    /**
     * Sets the value of the firstTimeInUK property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFirstTimeInUK(Boolean value) {
        this.firstTimeInUK = value;
    }

    /**
     * Gets the value of the repairedOrModified property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRepairedOrModified() {
        return repairedOrModified;
    }

    /**
     * Sets the value of the repairedOrModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRepairedOrModified(Boolean value) {
        this.repairedOrModified = value;
    }

    /**
     * Gets the value of the visitedPorts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitedPorts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitedPorts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_Port }
     * 
     * 
     */
    public List<T_Port> getVisitedPorts() {
        if (visitedPorts == null) {
            visitedPorts = new ArrayList<T_Port>();
        }
        return this.visitedPorts;
    }

    /**
     * Gets the value of the ukvatPaid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUKVATPaid() {
        return ukvatPaid;
    }

    /**
     * Sets the value of the ukvatPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUKVATPaid(Boolean value) {
        this.ukvatPaid = value;
    }

}
