//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_HireOrCharter.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="T_HireOrCharter">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Charter"/>
 *     &lt;enumeration value="Hire"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "T_HireOrCharter")
@XmlEnum
public enum T_HireOrCharter {

    @XmlEnumValue("Charter")
    CHARTER("Charter"),
    @XmlEnumValue("Hire")
    HIRE("Hire"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    T_HireOrCharter(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static T_HireOrCharter fromValue(String v) {
        for (T_HireOrCharter c: T_HireOrCharter.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
