//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for T_IMO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_IMO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IMOPort" minOccurs="0"/>
 *         &lt;element ref="{}IMONumber" minOccurs="0"/>
 *         &lt;element ref="{}IMODate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_IMO", propOrder = {
    "imoPort",
    "imoNumber",
    "imoDate"
})
public class T_IMO {

    @XmlElement(name = "IMOPort")
    protected T_Port imoPort;
    @XmlElement(name = "IMONumber")
    protected String imoNumber;
    @XmlElement(name = "IMODate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar imoDate;

    /**
     * Gets the value of the imoPort property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getIMOPort() {
        return imoPort;
    }

    /**
     * Sets the value of the imoPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setIMOPort(T_Port value) {
        this.imoPort = value;
    }

    /**
     * Gets the value of the imoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMONumber() {
        return imoNumber;
    }

    /**
     * Sets the value of the imoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMONumber(String value) {
        this.imoNumber = value;
    }

    /**
     * Gets the value of the imoDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIMODate() {
        return imoDate;
    }

    /**
     * Sets the value of the imoDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIMODate(XMLGregorianCalendar value) {
        this.imoDate = value;
    }

}
