//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for T_Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_Person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GivenName" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Surname"/>
 *         &lt;element ref="{}IsCrew" minOccurs="0"/>
 *         &lt;element ref="{}Nationality" minOccurs="0"/>
 *         &lt;element ref="{}TravelDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Gender" minOccurs="0"/>
 *         &lt;element ref="{}PlaceOfBirth" minOccurs="0"/>
 *         &lt;element ref="{}DateOfbirth" minOccurs="0"/>
 *         &lt;element ref="{}TransitPassenger" minOccurs="0"/>
 *         &lt;element ref="{}RankRating" minOccurs="0"/>
 *         &lt;element ref="{}CrewAllowances" minOccurs="0"/>
 *         &lt;element ref="{}HomeAddress" minOccurs="0"/>
 *         &lt;element ref="{}VisitingAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PurposeOfVisit" minOccurs="0"/>
 *         &lt;element ref="{}DurationOfStayInUK" minOccurs="0"/>
 *         &lt;element ref="{}IsVisaHolder" minOccurs="0"/>
 *         &lt;element ref="{}ContactNumber" maxOccurs="3" minOccurs="0"/>
 *         &lt;element ref="{}PortOfEmbarkation" minOccurs="0"/>
 *         &lt;element ref="{}PortOfDissembarkation" minOccurs="0"/>
 *         &lt;element ref="{}Cabin" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_Person", propOrder = {
    "givenName",
    "surname",
    "isCrew",
    "nationality",
    "travelDocument",
    "gender",
    "placeOfBirth",
    "dateOfbirth",
    "transitPassenger",
    "rankRating",
    "crewAllowances",
    "homeAddress",
    "visitingAddress",
    "purposeOfVisit",
    "durationOfStayInUK",
    "isVisaHolder",
    "contactNumber",
    "portOfEmbarkation",
    "portOfDissembarkation",
    "cabin"
})
public class T_Person {

    @XmlElement(name = "GivenName", required = true)
    protected List<String> givenName;
    @XmlElement(name = "Surname", required = true)
    protected String surname;
    @XmlElement(name = "IsCrew")
    protected Boolean isCrew;
    @XmlElement(name = "Nationality")
    protected String nationality;
    @XmlElement(name = "TravelDocument")
    protected List<T_TravelDocument> travelDocument;
    @XmlElement(name = "Gender")
    @XmlSchemaType(name = "string")
    protected T_Gender gender;
    @XmlElement(name = "PlaceOfBirth")
    protected String placeOfBirth;
    @XmlElement(name = "DateOfbirth")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfbirth;
    @XmlElement(name = "TransitPassenger")
    protected Boolean transitPassenger;
    @XmlElement(name = "RankRating")
    protected String rankRating;
    @XmlElement(name = "CrewAllowances")
    protected T_CrewAllowances crewAllowances;
    @XmlElement(name = "HomeAddress")
    protected T_Address homeAddress;
    @XmlElement(name = "VisitingAddress")
    protected List<T_Address> visitingAddress;
    @XmlElement(name = "PurposeOfVisit")
    @XmlSchemaType(name = "string")
    protected T_PurposeOfVisit purposeOfVisit;
    @XmlElement(name = "DurationOfStayInUK")
    protected String durationOfStayInUK;
    @XmlElement(name = "IsVisaHolder")
    protected Boolean isVisaHolder;
    @XmlElement(name = "ContactNumber")
    protected List<T_ContactNumber> contactNumber;
    @XmlElement(name = "PortOfEmbarkation")
    protected T_Port portOfEmbarkation;
    @XmlElement(name = "PortOfDissembarkation")
    protected T_Port portOfDissembarkation;
    @XmlElement(name = "Cabin")
    protected String cabin;

    /**
     * Gets the value of the givenName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the givenName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGivenName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGivenName() {
        if (givenName == null) {
            givenName = new ArrayList<String>();
        }
        return this.givenName;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the isCrew property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCrew() {
        return isCrew;
    }

    /**
     * Sets the value of the isCrew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCrew(Boolean value) {
        this.isCrew = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the travelDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_TravelDocument }
     * 
     * 
     */
    public List<T_TravelDocument> getTravelDocument() {
        if (travelDocument == null) {
            travelDocument = new ArrayList<T_TravelDocument>();
        }
        return this.travelDocument;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link T_Gender }
     *     
     */
    public T_Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Gender }
     *     
     */
    public void setGender(T_Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the dateOfbirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfbirth() {
        return dateOfbirth;
    }

    /**
     * Sets the value of the dateOfbirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfbirth(XMLGregorianCalendar value) {
        this.dateOfbirth = value;
    }

    /**
     * Gets the value of the transitPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTransitPassenger() {
        return transitPassenger;
    }

    /**
     * Sets the value of the transitPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransitPassenger(Boolean value) {
        this.transitPassenger = value;
    }

    /**
     * Gets the value of the rankRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRankRating() {
        return rankRating;
    }

    /**
     * Sets the value of the rankRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRankRating(String value) {
        this.rankRating = value;
    }

    /**
     * Gets the value of the crewAllowances property.
     * 
     * @return
     *     possible object is
     *     {@link T_CrewAllowances }
     *     
     */
    public T_CrewAllowances getCrewAllowances() {
        return crewAllowances;
    }

    /**
     * Sets the value of the crewAllowances property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_CrewAllowances }
     *     
     */
    public void setCrewAllowances(T_CrewAllowances value) {
        this.crewAllowances = value;
    }

    /**
     * Gets the value of the homeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link T_Address }
     *     
     */
    public T_Address getHomeAddress() {
        return homeAddress;
    }

    /**
     * Sets the value of the homeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Address }
     *     
     */
    public void setHomeAddress(T_Address value) {
        this.homeAddress = value;
    }

    /**
     * Gets the value of the visitingAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitingAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitingAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_Address }
     * 
     * 
     */
    public List<T_Address> getVisitingAddress() {
        if (visitingAddress == null) {
            visitingAddress = new ArrayList<T_Address>();
        }
        return this.visitingAddress;
    }

    /**
     * Gets the value of the purposeOfVisit property.
     * 
     * @return
     *     possible object is
     *     {@link T_PurposeOfVisit }
     *     
     */
    public T_PurposeOfVisit getPurposeOfVisit() {
        return purposeOfVisit;
    }

    /**
     * Sets the value of the purposeOfVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_PurposeOfVisit }
     *     
     */
    public void setPurposeOfVisit(T_PurposeOfVisit value) {
        this.purposeOfVisit = value;
    }

    /**
     * Gets the value of the durationOfStayInUK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationOfStayInUK() {
        return durationOfStayInUK;
    }

    /**
     * Sets the value of the durationOfStayInUK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationOfStayInUK(String value) {
        this.durationOfStayInUK = value;
    }

    /**
     * Gets the value of the isVisaHolder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsVisaHolder() {
        return isVisaHolder;
    }

    /**
     * Sets the value of the isVisaHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsVisaHolder(Boolean value) {
        this.isVisaHolder = value;
    }

    /**
     * Gets the value of the contactNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_ContactNumber }
     * 
     * 
     */
    public List<T_ContactNumber> getContactNumber() {
        if (contactNumber == null) {
            contactNumber = new ArrayList<T_ContactNumber>();
        }
        return this.contactNumber;
    }

    /**
     * Gets the value of the portOfEmbarkation property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getPortOfEmbarkation() {
        return portOfEmbarkation;
    }

    /**
     * Sets the value of the portOfEmbarkation property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setPortOfEmbarkation(T_Port value) {
        this.portOfEmbarkation = value;
    }

    /**
     * Gets the value of the portOfDissembarkation property.
     * 
     * @return
     *     possible object is
     *     {@link T_Port }
     *     
     */
    public T_Port getPortOfDissembarkation() {
        return portOfDissembarkation;
    }

    /**
     * Sets the value of the portOfDissembarkation property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Port }
     *     
     */
    public void setPortOfDissembarkation(T_Port value) {
        this.portOfDissembarkation = value;
    }

    /**
     * Gets the value of the cabin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCabin() {
        return cabin;
    }

    /**
     * Sets the value of the cabin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCabin(String value) {
        this.cabin = value;
    }

}
