//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_Port complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_Port">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}IATA"/>
 *         &lt;element ref="{}ICAO"/>
 *         &lt;element ref="{}UNLOCODE"/>
 *         &lt;element ref="{}LatLongPair"/>
 *         &lt;element ref="{}FullAddress"/>
 *         &lt;element ref="{}Description"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_Port", propOrder = {
    "iata",
    "icao",
    "unlocode",
    "latLongPair",
    "fullAddress",
    "description"
})
public class T_Port {

    @XmlElement(name = "IATA")
    protected String iata;
    @XmlElement(name = "ICAO")
    protected String icao;
    @XmlElement(name = "UNLOCODE")
    protected String unlocode;
    @XmlElement(name = "LatLongPair")
    protected T_LatLongPair latLongPair;
    @XmlElement(name = "FullAddress")
    protected T_Address fullAddress;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the iata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIATA() {
        return iata;
    }

    /**
     * Sets the value of the iata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIATA(String value) {
        this.iata = value;
    }

    /**
     * Gets the value of the icao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICAO() {
        return icao;
    }

    /**
     * Sets the value of the icao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICAO(String value) {
        this.icao = value;
    }

    /**
     * Gets the value of the unlocode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNLOCODE() {
        return unlocode;
    }

    /**
     * Sets the value of the unlocode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNLOCODE(String value) {
        this.unlocode = value;
    }

    /**
     * Gets the value of the latLongPair property.
     * 
     * @return
     *     possible object is
     *     {@link T_LatLongPair }
     *     
     */
    public T_LatLongPair getLatLongPair() {
        return latLongPair;
    }

    /**
     * Sets the value of the latLongPair property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_LatLongPair }
     *     
     */
    public void setLatLongPair(T_LatLongPair value) {
        this.latLongPair = value;
    }

    /**
     * Gets the value of the fullAddress property.
     * 
     * @return
     *     possible object is
     *     {@link T_Address }
     *     
     */
    public T_Address getFullAddress() {
        return fullAddress;
    }

    /**
     * Sets the value of the fullAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link T_Address }
     *     
     */
    public void setFullAddress(T_Address value) {
        this.fullAddress = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
