//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:15:23 AM GMT 
//


package com.fincore.cbp.stt.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_ReasonForVisit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="T_ReasonForVisit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Based"/>
 *     &lt;enumeration value="Maintenance"/>
 *     &lt;enumeration value="PermanentImport"/>
 *     &lt;enumeration value="Repair"/>
 *     &lt;enumeration value="ShortTermVisit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "T_ReasonForVisit")
@XmlEnum
public enum T_ReasonForVisit {

    @XmlEnumValue("Based")
    BASED("Based"),
    @XmlEnumValue("Maintenance")
    MAINTENANCE("Maintenance"),
    @XmlEnumValue("PermanentImport")
    PERMANENT_IMPORT("PermanentImport"),
    @XmlEnumValue("Repair")
    REPAIR("Repair"),
    @XmlEnumValue("ShortTermVisit")
    SHORT_TERM_VISIT("ShortTermVisit");
    private final String value;

    T_ReasonForVisit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static T_ReasonForVisit fromValue(String v) {
        for (T_ReasonForVisit c: T_ReasonForVisit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
